services:
  whatsapp_web_api:
    container_name: whatsapp_web_api
    build: .
    restart: always
    env_file:
      - .env
    ports:
      - "8099:3000"
    volumes:
      - whatsapp_web_api_data:/usr/src/app/sessions
    networks:
      - database_network

volumes:
  whatsapp_web_api_data:

networks:
  database_network:
    external: true
